#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
export CHATID="2118266757"
export KEY="6560040848:AAGSiQw_SO-wML_vbY8AYUFIvKrF_iC_Reo"
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear
# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://sc1.bagusvpn.me/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          Julak Bantur Autoscript          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/Cibut2d"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6281250851741"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
echo -e "\e[32mloading...\e[0m"
clear
#Domain
domain=$(cat /etc/xray/domain)

echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "                SSH & OpenVPN           "
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "  ${ORANGE}[01]${NC}\033[0;36m Buat akun ${NC}"
echo -e "  ${ORANGE}[02]${NC}\033[0;36m Tambah masa aktif ${NC}"
echo -e "  ${ORANGE}[03]${NC}\033[0;36m Hapus akun ${NC}"
echo -e "  ${ORANGE}[04]${NC}\033[0;36m Cek online akun SSH ${NC}"
echo -e "  ${ORANGE}[05]${NC}\033[0;36m Cek online akun UDP ${NC}"
echo -e "  ${ORANGE}[06]${NC}\033[0;36m Cek Member ${NC}"
echo -e "  ${ORANGE}[07]${NC}\033[0;36m Cek detail akun${NC}"
echo -e "  ${ORANGE}[08]${NC}\033[0;36m Kunci akun ${NC}"
echo -e "  ${ORANGE}[09]${NC}\033[0;36m Buka kunci akun ${NC}"
echo -e "  ${ORANGE}[10]${NC}\033[0;36m On Off limit IP ${NC}"
echo -e "  ${ORANGE}[11]${NC}\033[0;36m Ganti Limit IP ${NC}"
echo -e "  ${ORANGE}[12]${NC}\033[0;36m Buat akun trial ${NC}"
echo -e "  ${ORANGE}[13]${NC}\033[0;36m Cek akun multilogin ${NC}"
echo -e "  ${ORANGE}[14]${NC}\033[0;36m Hapus akun expired ${NC}"
echo -e "  ${ORANGE}[00]${NC}\033[0;36m Kembali ke menu utama ${NC}"
echo -e "  ${ORANGE}[99]${NC}\033[0;36m Keluar ${NC}"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
read -p "Select From Options [ 0 - 99 ] : " menu
echo -e ""
case $menu in
1)
    addssh
    ;;
2)
    renewssh
    ;;
3)
    delssh
    ;;
4)
    cekssh
    ;;
5)
    cekudp
    ;;
6)
    member
    ;;
7)
    user-ssh
    ;;
8)
    lock
    ;;
9)
    unlock
    ;;
10)
    cibut-onoff
    ;;
11)
    ganti-ip
    ;;
12)
    trial
    ;;
13)
    ceklim
    ;;
14)
    delexp
    ;;
0)
    menu
    ;;
99)
    exit
    ;;
*)
    m-sshws
    ;;
esac