#!/bin/bash

# Function to display ASCII loading animation
loading_animation() {
    # List of ASCII art frames for loading animation
    frames=(
        " [\e[36m•\e[0m]\e[37m"
        " [\e[36m•\e[0m]\e[37m.\e[37m"
        " [\e[36m•\e[0m]\e[37m..\e[37m"
        " [\e[36m•\e[0m]\e[37m...\e[37m"
        " [\e[36m•\e[0m]\e[37m...\e[37m \e[36m•\e[0m\e[37m"
        " [\e[36m•\e[0m]\e[37m...\e[37m \e[36m•\e[0m\e[37m \e[36m•\e[0m\e[37m"
        " [\e[36m•\e[0m]\e[37m...\e[37m \e[36m•\e[0m\e[37m \e[36m•\e[0m\e[37m \e[36m•\e[0m\e[37m"
        " [\e[36m•\e[0m]\e[37m...\e[37m \e[36m•\e[0m\e[37m \e[36m•\e[0m\e[37m \e[36m•\e[0m\e[37m \e[36m•\e[0m\e[37m"
    )

    # Loop through each frame and display it with a delay
    for frame in "${frames[@]}"; do
        echo -ne "$frame\r"
        sleep 0.5
    done
}

# Function to display the menu
display_menu() {
    # Clear the screen
    clear

    # Define colors
    cyan='\e[36m'
    NC='\e[0m'

    # Display ASCII art for menu header
    echo -e "${cyan}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${cyan}             • Backup Menu •         ${NC}"
    echo -e "${cyan}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "" 
    echo -e " [\e[36m•1\e[0m] Backup VPS Data"
    echo -e " [\e[36m•2\e[0m] Restore VPS Data"
    echo -e " [\e[36m•3\e[0m] AutoBackup VPS Data"
    echo -e " [\e[36m•4\e[0m] Backup via Telegram"
    echo -e "" 
    echo -e " [\e[31m•0\e[0m] \e[31mBack To Menu\033[0m"
    echo -e "" 
    echo -e "${cyan}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e ""
}

# Display the loading text
echo -e "\n${cyan}Loading...${NC}"

# Display the loading animation
loading_animation &

# Wait for 5 seconds
sleep 5

# Kill the loading animation process
kill $!

# Display the menu
display_menu

# Prompt user for menu selection
read -p " Select menu :  "  opt
echo -e ""

# Handle user's menu selection
case $opt in
01 | 1) clear ; backup ;;
02 | 2) clear ; restore ;;
03 | 3) clear ; autobackup ;;
04 | 4) clear ; mbot ;;
00 | 0) clear ; menu ;;
*) clear ; menu-backup ;;
esac
