#!/bin/bash

# Warna
ORANGE='\033[0;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${ORANGE}
  ____        _       _   _             
 / ___|  ___ | |_   _| |_(_)_ __   __ _ 
 \___ \ / _ \| | | | | __| | '_ \ / _\` |
  ___) | (_) | | |_| | |_| | | | | (_| |
 |____/ \___/|_|\__,_|\__|_|_| |_|\__, |
                                   |___/ 
${NC}"
echo -e "${ORANGE}=== Unlock Menu ===${NC}"
echo -e " ${CYAN}1.${NC} ${ORANGE}Unlock ${CYAN}VMess${NC} ${ORANGE}User${NC}"
echo -e " ${CYAN}2.${NC} ${ORANGE}Unlock ${CYAN}VLESS${NC} ${ORANGE}User${NC}"
echo -e " ${CYAN}3.${NC} ${ORANGE}Unlock ${CYAN}Trojan${NC} ${ORANGE}User${NC}"
echo -e " ${CYAN}4.${NC} ${RED}Exit${NC}"

read -p "Enter your choice: " choice

case $choice in
    1)
        unlock-ws
        ;;
    2)
        unlock-vl
        ;;
    3)
        unlock-tr
        ;;
    4)
        echo "Exiting..."
        exit 0
        ;;
    *)
        echo "Invalid option. Please try again."
        ;;
esac