#!/bin/bash
function julak() {
echo -e "\e[33m──────────────────────────────────────────\033[0m"
}

function unlock(){
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/xray/config.json")
	if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        julak
        echo -e "\E[40;1;37m          LIST MEMBER V2RAY VMESS         \E[0m"
        sanakstore      
		echo -e ""
		echo -e "You Don't Have a Vmess Account!"
		echo -e ""
        julak      
		read -n 1 -s -r -p "Press any key to back"
        menu
	fi

	clear
    julak
    echo -e "\E[40;1;37m          DAPTAR AKUN V2RAY VMESS         \E[0m"
    julak 
    echo -e "USER          EXPIRED" 
    julak 
	grep -e "^### " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq
    echo -e ""
    echo -e "\e[1;31mTekan Enter Untuk Kembali\033[0m"
     julak
	read -rp "Masukkan Username : " user
    if [ -z $user ]; then
    menu
    else
    exp=$(grep -wE "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    sed -i "/### $user /{n;s/^#//}" /etc/xray/config.json
    systemctl restart xray > /dev/null 2>&1
    clear
    julak
    echo -e "\E[40;1;37m       BERHASIL UNLOCK AKUN VMESS       \E[0m"
    julak
    echo -e ""
    echo -e "${NC}Info Username   : $user"
    echo -e "${NC}Masa Aktif Akun : $exp"
    echo -e "${NC}Status Unlocked : Success"
    echo -e "Terima kasih telah menggunakan script by Julak Bantur."
    echo -e ""
    julak
    echo -e ""
    read -n 1 -s -r -p "Press any key to back"
    menu
    fi
}
# Panggil fungsi untuk membuka kunci akses pengguna XRAY
unlock